# Generated by Django 3.1.1 on 2020-10-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_date', models.DateField()),
                ('movie_name', models.CharField(max_length=64)),
                ('hero', models.CharField(max_length=64)),
                ('heroine', models.CharField(max_length=64)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
